name: "Update Pull Request"

on: pull_request

jobs:
  update_pr:
    runs-on: ubuntu-latest
    outputs:
      baseMatch: ${{ steps.update_pr.outputs.baseMatch }}
      headMatch: ${{ steps.update_pr.outputs.headMatch }}
      titleUpdated: ${{ steps.update_pr.outputs.titleUpdated }}
      bodyUpdated: ${{ steps.update_pr.outputs.bodyUpdated }}
    steps:
      - id: update_pr
        uses: the-wright-jamie/update-pr-info-action
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '[a-z\d-_.\/]+'
          title-template: "[updated-by-action]"
          body-template: "[Updated by Pull Request Updater action] The head branch is %headbranch% and the base branch is %basebranch%"
  update_pr_outputs:
    runs-on: ubuntu-latest
    needs: update_pr
    steps:
      - run: |
          echo 'baseMatch:' ${{needs.update_pr.outputs.baseMatch}}
          echo 'headMatch:' ${{needs.update_pr.outputs.headMatch}}
          echo 'titleUpdated:' ${{needs.update_pr.outputs.titleUpdated}}
          echo 'bodyUpdated:' ${{needs.update_pr.outputs.bodyUpdated}}
